# Generated by Django 4.1.5 on 2023-01-15 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web3_auth", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="uri_collection",
            new_name="uri_asset",
        ),
    ]
