# Generated by Django 4.1.5 on 2023-01-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web3_auth", "0002_rename_uri_collection_asset_uri_asset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collection",
            old_name="metadata_uri",
            new_name="uri_metadata",
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("image", "Image File"),
                    ("audio", "Audio File"),
                    ("video", "Video File"),
                    ("file", "Generic File"),
                    ("other", "Other Type"),
                ],
                default="image",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="collection_type",
            field=models.CharField(
                choices=[
                    ("image", "Image File"),
                    ("audio", "Audio Files"),
                    ("video", "Video Files"),
                    ("file", "Generic Files"),
                    ("misc", "Misc. Types"),
                ],
                default="image",
                max_length=32,
            ),
        ),
    ]
