# Generated by Django 4.0.1 on 2022-05-29 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('bid_price', models.FloatField()),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-bid_price',),
            },
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nft_name', models.CharField(max_length=50)),
                ('token_id', models.IntegerField(default=main.models.random_token)),
                ('metadata_uri', models.URLField()),
                ('blockchain', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_ends', models.DateField()),
                ('min_bid_price', models.FloatField()),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nft')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tx_hash', models.CharField(max_length=200)),
                ('sale_time', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bid')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(blank=True, max_length=36, null=True)),
                ('wallet_private_key', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nft')),
            ],
        ),
        migrations.CreateModel(
            name='NFTCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('token_id', models.IntegerField(default=main.models.random_token)),
                ('blockchain', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nfts', models.ManyToManyField(related_name='nfts', to='main.NFT')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nft'),
        ),
    ]
