# Generated by Django 4.1 on 2022-08-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="bid_current_value",
            field=models.FloatField(default=None),
        ),
    ]
