# Generated by Django 4.1 on 2022-08-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_auction_bid_current_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="bid_current_value",
            field=models.FloatField(default=0),
        ),
    ]
