# Generated by Django 4.1.1 on 2022-09-10 17:34

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_auction_bid_current_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="date_start",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="time_end",
        ),
        migrations.RemoveField(
            model_name="auction",
            name="time_start",
        ),
        migrations.RemoveField(
            model_name="raffle",
            name="date_end",
        ),
        migrations.RemoveField(
            model_name="raffle",
            name="date_start",
        ),
        migrations.RemoveField(
            model_name="raffle",
            name="time_end",
        ),
        migrations.RemoveField(
            model_name="raffle",
            name="time_start",
        ),
        migrations.AddField(
            model_name="auction",
            name="datetime_end",
            field=models.DateTimeField(default=main.models.now_plus_30),
        ),
        migrations.AddField(
            model_name="auction",
            name="datetime_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="raffle",
            name="datetime_end",
            field=models.DateTimeField(default=main.models.now_plus_30),
        ),
        migrations.AddField(
            model_name="raffle",
            name="datetime_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
