# Generated by Django 4.1.1 on 2022-09-10 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_auction_date_end_remove_auction_date_start_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raffle",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.asset",
            ),
        ),
        migrations.AlterField(
            model_name="raffle",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
