# Generated by Django 4.1 on 2022-09-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_raffle_asset_alter_raffle_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="auction",
        ),
        migrations.AddField(
            model_name="auction",
            name="bids",
            field=models.ManyToManyField(related_name="bids", to="main.bid"),
        ),
    ]
