# Generated by Django 4.1.1 on 2022-09-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_bid_auction_auction_bids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="status",
            field=models.CharField(
                choices=[("unsold", "Unsold"), ("sold", "Sold")],
                default="unsold",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[("unsold", "Unsold"), ("sold", "Sold")],
                default="scheduled",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("aborted", "Purchase Aborted"),
                    ("running", "Puchase in Progress"),
                    ("complete", "Purchase Complete"),
                ],
                default="running",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="raffle",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_won", "raffle ended without winners"),
                    ("won", "raffle ended with winners"),
                ],
                default="scheduled",
                max_length=32,
            ),
        ),
    ]
