# Generated by Django 4.1.1 on 2022-09-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_asset_status_alter_auction_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="bids",
        ),
        migrations.AddField(
            model_name="bid",
            name="auction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.auction",
            ),
        ),
    ]
