# Generated by Django 4.1 on 2022-09-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_auction_bids_bid_auction"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="uri_preview",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="uri_preview",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("image", "Image File"),
                    ("audio", "Audio Files"),
                    ("video", "Video Files"),
                    ("file", "Generic Files"),
                    ("misc", "Misc. Types"),
                ],
                default="2d",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="nft",
            name="nft_type",
            field=models.CharField(
                choices=[
                    ("image", "Image File"),
                    ("audio", "Audio File"),
                    ("video", "Video File"),
                    ("file", "Generic File"),
                    ("other", "Other Type"),
                ],
                default="2d",
                max_length=32,
            ),
        ),
    ]
