# Generated by Django 4.1.1 on 2022-09-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_asset_uri_preview_auction_uri_preview_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="blockchain",
        ),
        migrations.AddField(
            model_name="auction",
            name="contract_abi",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="contract_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auction",
            name="network",
            field=models.CharField(
                choices=[
                    ("matic_main", "matic_main"),
                    ("mumbay", "mumbay"),
                    ("rinkeby", "rinkeby"),
                ],
                default="rinkeby",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[("unsold", "Unsold"), ("sold", "Sold")],
                default="unsold",
                max_length=32,
            ),
        ),
    ]
