# Generated by Django 4.1 on 2022-09-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_auction_blockchain_auction_contract_abi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="network",
            field=models.CharField(
                choices=[
                    ("matic_main", "matic_main"),
                    ("mumbai", "mumbai"),
                    ("rinkeby", "rinkeby"),
                ],
                default="rinkeby",
                max_length=32,
            ),
        ),
    ]
