# Generated by Django 4.1.1 on 2022-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_auction_network"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="network",
            field=models.CharField(
                choices=[
                    ("matic_main", "matic_main"),
                    ("mumbai", "mumbai"),
                    ("goerli", "goerli"),
                    ("rinkeby", "rinkeby"),
                ],
                default="rinkeby",
                max_length=32,
            ),
        ),
    ]
