# Generated by Django 4.1 on 2022-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_auction_network"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auction",
            name="contract_abi",
        ),
        migrations.AlterField(
            model_name="auction",
            name="contract_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
