# Generated by Django 4.1 on 2022-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_auction_contract_abi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="status",
            field=models.CharField(
                choices=[("unsold", "Unsold"), ("sold", "Sold")],
                default="unsold",
                max_length=32,
            ),
        ),
    ]
